cc_library(
    name = "bbts_lib",
    alwayslink = 1,
    deps = [
        "//main/commands:commands",
        "//main/communication:communication",
        "//main/operations:operations",
        "//main/server:server",
        "//main/storage:storage",
        "//main/tensor:tensor",
        "//main/ud_functions:ud_functions"],
    visibility = ["//visibility:public"],
)